/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school;

import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class mainProgram extends javax.swing.JFrame {

    static Connection con;
    static Statement stmt;
    ResultSet rs;
    DefaultTableModel model;
    DefaultTableModel modelMarks;
    DefaultTableModel modelTeachar;
    int currentRow;

    /**
     * Creates new form mainProgram
     */
    public mainProgram() throws IOException {
        initComponents();
        try {
            jComboBoxMain.removeAllItems();
            jComboBoxMain.addItem("All");
            ResultSet rs = connectionToDatabase("SELECT class.name\n"
                    + "FROM class;");
            while (rs.next()) {
                jComboBoxMain.addItem(rs.getString(1));
            }

        } catch (Exception e) {
        }
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBoxMain = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jfirstName = new javax.swing.JTextField();
        jMiddleName = new javax.swing.JTextField();
        jMobile = new javax.swing.JTextField();
        jLastName = new javax.swing.JTextField();
        jAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFirstTeacher = new javax.swing.JTextField();
        jLastTeacher = new javax.swing.JTextField();
        jMobileTeacher = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxTeacher = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTeachar = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMarks = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxMarks = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jComboBoxSubject = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("main program");

        jTable2.setBackground(new java.awt.Color(102, 255, 102));
        jTable2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Middile Name", "Last Name", "Mobile", "Address", "Class", "Average"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(51, 255, 51));
        jTable2.setSelectionForeground(new java.awt.Color(255, 0, 0));
        jScrollPane2.setViewportView(jTable2);

        jComboBoxMain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMainActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Search :");

        jTextFieldSearch.setSelectionColor(new java.awt.Color(51, 255, 0));
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("Search");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton15.setText("Delete Student");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton16.setText("Update Student");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton16))))
                    .addComponent(jComboBoxMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 150, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jComboBoxMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jButton14)
                        .addGap(36, 36, 36)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("first Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Middle Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("last Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("mobile :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Add Student to Class");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jButton2)
                .addContainerGap(342, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addGap(92, 92, 92))
        );

        jButton3.setText("Main");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Add Student");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Create Calss");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Teacher");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setText("First Name :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setText("Last Name :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel9.setText("Mobile :");

        jFirstTeacher.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jFirstTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstTeacherActionPerformed(evt);
            }
        });

        jLastTeacher.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        jMobileTeacher.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Add Teachar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Add Teacher to School");

        jComboBoxTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTeacherActionPerformed(evt);
            }
        });

        jTableTeachar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Mobile", "subject"
            }
        ));
        jScrollPane3.setViewportView(jTableTeachar);

        jButton12.setText("Delete");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Add Money");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel10)
                .addContainerGap(289, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton13))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jButton7)
                                    .addGap(81, 81, 81)
                                    .addComponent(jComboBoxTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jMobileTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLastTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(jFirstTeacher))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jFirstTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLastTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jMobileTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(jComboBoxTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton12)
                            .addComponent(jButton13)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jButton8.setText("Add subject");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTableMarks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "mark"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMarks);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Add Marks");

        jComboBoxMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarksActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButton10.setText("Save");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jComboBoxSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButton10)
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxSubject, 0, 100, Short.MAX_VALUE)
                                    .addComponent(jComboBoxMarks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel11)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jComboBoxMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jComboBoxSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jButton1.setText("Add Marks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton9.setText("Add Money");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton11.setText("Delete Class");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton9)
                    .addComponent(jButton11))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(182, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(257, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 215, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 216, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 227, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 227, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(27, 27, 27)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(34, 34, 34)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(29, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);

        jComboBox1.removeAllItems();
        try {

            ResultSet rs1 = connectionToDatabase("SELECT name FROM class;");

            while (rs1.next()) {
                jComboBox1.addItem(rs1.getString(1));

            }
            rs1.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {

            if (!jfirstName.getText().equals("")) {

                createAccount();
                ResultSet rs2 = connectionToDatabase("SELECT class.id_class FROM  class WHERE class.name='" + jComboBox1.getSelectedItem() + "';");
                rs2.first();
                ResultSet rs3 = connectionToDatabase("SELECT account.id_account  FROM account \n"
                        + "ORDER BY account.id_account DESC LIMIT 1; ");
                rs3.first();
                updateOnDatabase("INSERT INTO student VALUES(NULL,'" + jfirstName.getText() + "','" + jMiddleName.getText() + "',"
                        + "'" + jLastName.getText() + "'"
                        + ",'" + jMobile.getText() + "','" + jAddress.getText() + "'," + rs2.getInt(1) + "," + rs3.getInt(1) + " )");

                jfirstName.setText("");
                jMiddleName.setText("");
                jLastName.setText("");
                jMobile.setText("");
                jAddress.setText("");
                rs2.close();
                rs3.close();
                JOptionPane.showMessageDialog(null, "Done");
            } else {
                JOptionPane.showMessageDialog(null, "please Enter name...");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private void createAccount() {
        String URL = "jdbc:mysql://localhost/";
        String DBName = "school";
        String driver = "com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "";

        try {
            Class.forName(driver);
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection(URL + DBName, userName, password);
            com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);

            int rs = stmt.executeUpdate("INSERT INTO account VALUES(NULL,0);");

        } catch (Exception e) {
        }

    }

    public static void updateOnDatabase(String query) {
        String URL = "jdbc:mysql://localhost/";
        String DBName = "school";
        String driver = "com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "";
        try {
            Class.forName(driver);
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection(URL + DBName, userName, password);
            com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);

            stmt.executeUpdate(query);

        } catch (Exception ex) {
        }
    }

    public static ResultSet connectionToDatabase(String query) {

        String URL = "jdbc:mysql://localhost/";
        String DBName = "school";
        String driver = "com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "";
        ResultSet rs = null;
        try {
            Class.forName(driver);
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection(URL + DBName, userName, password);
            com.mysql.jdbc.Statement stmt = (com.mysql.jdbc.Statement) con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);

            rs = stmt.executeQuery(query);

        } catch (Exception ex) {
        }
        return rs;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new mainProgram().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(mainProgram.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    private int getNumberRowAccount() {

        ResultSet rs = null;
        int n = 0;
        try {

            rs = connectionToDatabase("SELECT COUNT(account.id_account)  FROM account;");
            rs.first();
            n = rs.getInt(1);
        } catch (Exception e) {
        }

        return n;
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);

        try {

            String nameClass = JOptionPane.showInputDialog(null, "Enter Name Class ...");
            if ((nameClass != null) && (!nameClass.equals(""))) {
                updateOnDatabase("INSERT INTO class VALUES(NULL,'" + nameClass + "');");

                jComboBoxMain.addItem(nameClass);
            }
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jFirstTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstTeacherActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
        jComboBoxTeacher.removeAllItems();
        jTableTeachar.setModel(new DefaultTableModel(null, new String[]{"First Name", "Last Name", "Mobile", "Subject"}));
        try {

            rs = connectionToDatabase("SELECT name FROM subject;");
            while (rs.next()) {
                jComboBoxTeacher.addItem(rs.getString(1));

            }
            rs.close();

        } catch (Exception ex) {
        }
        modelTeachar = (DefaultTableModel) jTableTeachar.getModel();
        try {
            ResultSet rs1 = connectionToDatabase("SELECT teacher.first_name,teacher.last_name,teacher.mobile,subject.name\n"
                    + "FROM teacher JOIN subject\n"
                    + "ON teacher.id_subject=subject.id_subject");
            while (rs1.next()) {
                modelTeachar.addRow(new Object[]{rs1.getString(1), rs1.getString(2), rs1.getString(3), rs1.getString(4)});
            }
            rs1.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (!jFirstTeacher.getText().equals("")) {

            try {

                updateOnDatabase("INSERT INTO teacher VALUES(NULL,'" + jFirstTeacher.getText() + "','" + jLastTeacher.getText()
                        + "','" + jMobileTeacher.getText() + "'," + (jComboBoxTeacher.getSelectedIndex() + 1) + ",0);");

                modelTeachar = (DefaultTableModel) jTableTeachar.getModel();
                modelTeachar.addRow(new Object[]{jFirstTeacher.getText(), jLastTeacher.getText(), jMobileTeacher.getText(), jComboBoxTeacher.getSelectedItem()});
                jFirstTeacher.setText("");
                jLastTeacher.setText("");
                jMobileTeacher.setText("");
                JOptionPane.showMessageDialog(null, "Done");

            } catch (Exception ex) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "please Enter name...");
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);

        try {

            String nameSubjct = JOptionPane.showInputDialog(null, "Enter Name Subject...");
            if ((nameSubjct != null) && (!nameSubjct.equals(""))) {
                updateOnDatabase("INSERT INTO subject VALUES(NULL,'" + nameSubjct + "');");
                JOptionPane.showMessageDialog(null, "Done");
            } else {
                JOptionPane.showMessageDialog(null, "Enter name Subject");
            }
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBoxTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTeacherActionPerformed

    }//GEN-LAST:event_jComboBoxTeacherActionPerformed

    private void jComboBoxMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMainActionPerformed

        jTable2.setModel(new DefaultTableModel(null, new String[]{"ID", "First Name", "Middle Name", "Last Name", "Mobile", "Address", "class", "Average"}));
        model = (DefaultTableModel) jTable2.getModel();
        ResultSet rs3 = null;
        if (jComboBoxMain.getSelectedItem().equals("All")) {
            ResultSet rs1 = connectionToDatabase("SELECT  student.id_student,student.first_name,student.middle_name,student.last_name,student.mobile,student.Address,class.name\n"
                    + "FROM student JOIN class\n"
                    + "ON student.id_class =class.id_class;");

            try {
                while (rs1.next()) {
                    rs3 = connectionToDatabase("SELECT AVG(marks.Amount) FROM marks JOIN student \n"
                            + "ON student.id_student=marks.id_student\n"
                            + "WHERE student.id_student=" + rs1.getInt(1) + ";");
                    rs3.first();
                    model.addRow(new Object[]{rs1.getInt(1), rs1.getString(2), rs1.getString(3), rs1.getString(4),
                        rs1.getString(5), rs1.getString(6), rs1.getString(7), rs3.getDouble(1)});
                }
                rs1.close();
                rs3.close();
            } catch (Exception e) {
            }
        } else {
            ResultSet rs2 = connectionToDatabase("SELECT\n"
                    + "    student.id_student,\n"
                    + "    student.first_name,\n"
                    + "    student.middle_name,\n"
                    + "    student.last_name,\n"
                    + "    student.mobile,\n"
                    + "    student.Address,\n"
                    + "    class.name\n"
                    + "FROM\n"
                    + "    student\n"
                    + "JOIN class ON student.id_class = class.id_class\n"
                    + "WHERE class.name='" + jComboBoxMain.getSelectedItem() + "';");
            try {
                while (rs2.next()) {
                    rs3 = connectionToDatabase("SELECT AVG(marks.Amount) FROM marks JOIN student \n"
                            + "ON student.id_student=marks.id_student\n"
                            + "WHERE student.id_student=" + rs2.getInt(1) + ";");
                    rs3.first();
                    model.addRow(new Object[]{rs2.getInt(1), rs2.getString(2), rs2.getString(3), rs2.getString(4),
                        rs2.getString(5), rs2.getString(6), rs2.getString(7), rs3.getDouble(1)});
                }
                rs2.close();
                rs3.close();
            } catch (Exception e) {
            }

        }


    }//GEN-LAST:event_jComboBoxMainActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel2.setVisible(false);
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jComboBoxMarks.removeAllItems();
        try {
            ResultSet rs = connectionToDatabase("SELECT class.name\n"
                    + "FROM class;");
            while (rs.next()) {
                jComboBoxMarks.addItem(rs.getString(1));
            }
            jComboBoxSubject.removeAllItems();
            ResultSet rs2 = connectionToDatabase("SELECT subject.name\n"
                    + "FROM subject;");
            while (rs2.next()) {
                jComboBoxSubject.addItem(rs2.getString(1));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarksActionPerformed
        jTableMarks.setModel(new DefaultTableModel(null, new String[]{"ID", "First Name", "Last Name", "Mark"}));
        modelMarks = (DefaultTableModel) jTableMarks.getModel();

        ResultSet rs2 = connectionToDatabase("SELECT\n"
                + "    student.id_student,\n"
                + "    student.first_name,\n"
                + "    student.last_name\n"
                + "FROM\n"
                + "    student\n"
                + "JOIN class ON student.id_class = class.id_class\n"
                + "WHERE class.name='" + jComboBoxMarks.getSelectedItem() + "';");

        try {
            while (rs2.next()) {
                modelMarks.addRow(new Object[]{rs2.getInt(1), rs2.getString(2), rs2.getString(3)});
            }
            rs2.close();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jComboBoxMarksActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        currentRow = jTable2.getSelectedRow();
        if (currentRow == -1) {
            JOptionPane.showConfirmDialog(null, "Do not Select Row Yet...!");
        } else {
            try {
                // model = (DefaultTableModel) jTable2.getModel();
                int id = (int) jTable2.getValueAt(currentRow, 0);
                ResultSet rs2 = connectionToDatabase("SELECT account.Amount  FROM account WHERE account.id_account=" + id);
                rs2.first();

                String str = JOptionPane.showInputDialog("Previous value : " + rs2.getInt(1) + "\nPlease Enter Value");
                int value = Integer.parseInt(str);
                updateOnDatabase("UPDATE  account SET account.Amount=" + value + "+(\n"
                        + "SELECT account.Amount  FROM account WHERE account.id_account=" + id + "\n"
                        + ")\n"
                        + "WHERE account.id_account=" + id + ";");
                JOptionPane.showMessageDialog(null, "Done");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {

            for (int i = 0; i < jTableMarks.getRowCount(); i++) {
                if (jTableMarks.getValueAt(i, 3) != null) {
                    ResultSet rs1 = connectionToDatabase("SELECT subject.id_subject FROM subject WHERE subject.name='" + jComboBoxSubject.getSelectedItem() + "';");
                    rs1.first();
                    updateOnDatabase("INSERT INTO marks VALUES (NULL," + jTableMarks.getValueAt(i, 3) + "," + rs1.getInt(1) + "," + jTableMarks.getValueAt(i, 0) + ");");
                    rs1.close();
                    jTableMarks.setValueAt("", i, 3);
                }
            }
            JOptionPane.showMessageDialog(null, "Done");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Not Save...!");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboBoxSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSubjectActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Object[] values = new String[jComboBoxMain.getMaximumRowCount() - 1];
        for (int i = 0; i < jComboBoxMain.getMaximumRowCount() - 1; i++) {
            values[i] = jComboBoxMain.getItemAt(i + 1);
        }
        try {

            Object t = JOptionPane.showInputDialog(null, "Select value", "", JOptionPane.PLAIN_MESSAGE, null, values, values[0]);
            int x = JOptionPane.showConfirmDialog(null,
                    "Do you certain ?",
                    "Warning",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if (x == 0) {
                ResultSet rs1 = connectionToDatabase("SELECT  class.id_class\n"
                        + "FROM class WHERE class.name ='" + t + "';");
                rs1.first();
                ResultSet rs3 = connectionToDatabase("SELECT student.id_student\n"
                        + "FROM student JOIN class\n"
                        + "ON student.id_class=class.id_class WHERE class.id_class=" + rs1.getInt(1) + ";");

                while (rs3.next()) {
                    updateOnDatabase("DELETE FROM notes WHERE notes.id_student=" + rs3.getInt(1) + ";");
                    updateOnDatabase("DELETE FROM marks WHERE marks.id_student=" + rs3.getInt(1) + " ;");
                    updateOnDatabase("DELETE FROM student WHERE student.id_student=" + rs3.getInt(1) + ";");
                    updateOnDatabase("DELETE FROM account WHERE account.id_account=" + rs3.getInt(1) + ";");
                }
                updateOnDatabase("DELETE FROM class WHERE class.id_class=" + rs1.getInt(1) + ";");
                rs1.close();
                rs3.close();
                jComboBoxMain.removeItem(t);
                jComboBoxMarks.removeItem(t);
                jComboBoxMarks.removeItem(t);
                JOptionPane.showMessageDialog(null, "Done");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        currentRow = jTableTeachar.getSelectedRow();
        if (currentRow == -1) {
            JOptionPane.showConfirmDialog(null, "Do not Select Row Yet...!");
        } else {
            try {
                // model = (DefaultTableModel) jTable2.getModel();
                ResultSet rs3 = connectionToDatabase("SELECT teacher.id_Teachar FROM teacher \n"
                        + "WHERE teacher.mobile='" + jTableTeachar.getValueAt(currentRow, 2) + "';");
                rs3.first();
                int id = rs3.getInt(1);
                rs3.close();
                ResultSet rs2 = connectionToDatabase("SELECT teacher.salary  FROM teacher WHERE teacher.id_Teachar=" + id);
                rs2.first();

                String str = JOptionPane.showInputDialog("Previous value : " + rs2.getInt(1) + "\nPlease Enter Value");
                int value = Integer.parseInt(str);
                updateOnDatabase("UPDATE  teacher SET teacher.salary =" + value + "+(\n"
                        + "SELECT teacher.salary   FROM teacher WHERE teacher.id_Teachar=" + id + "\n"
                        + ")\n"
                        + "WHERE teacher.id_Teachar=" + id + ";");
                rs2.close();
                JOptionPane.showMessageDialog(null, "Done");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        currentRow = jTableTeachar.getSelectedRow();
        if (currentRow == -1) {
            JOptionPane.showConfirmDialog(null, "Do not Select Row Yet...!");
        } else {
            try {
                // model = (DefaultTableModel) jTable2.getModel();
                ResultSet rs3 = connectionToDatabase("SELECT teacher.id_Teachar FROM teacher \n"
                        + "WHERE teacher.mobile='" + jTableTeachar.getValueAt(currentRow, 2) + "';");
                rs3.first();
                int id = rs3.getInt(1);
                rs3.close();
                updateOnDatabase("DELETE FROM teacher WHERE teacher.id_Teachar=" + id + ";");
                modelTeachar = (DefaultTableModel) jTableTeachar.getModel();
                modelTeachar.removeRow(currentRow);
                //   jTableTeachar.remove(currentRow);
                JOptionPane.showMessageDialog(null, "Done");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (jTextFieldSearch.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter Id for Student...!");
        } else {
            try {
                ResultSet rs1 = null;
                ResultSet rs2 = connectionToDatabase("SELECT student.id_student FROM student;");
                while (rs2.next()) {
                    if (rs2.getInt(1) == Integer.parseInt(jTextFieldSearch.getText())) {
                        rs1 = connectionToDatabase("SELECT student.first_name,student.middle_name,student.last_name,student.mobile,student.Address,class.name\n"
                                + "FROM student JOIN class\n"
                                + "ON student.id_class=class.id_class WHERE student.id_student=" + jTextFieldSearch.getText() + ";");
                        rs1.first();
                        JOptionPane.showMessageDialog(null, rs1.getString(1) + "  " + rs1.getString(2) + "  " + rs1.getString(3)
                                + "  " + rs1.getString(4) + "  " + rs1.getString(5) + "   " + rs1.getString(6));
                        jTextFieldSearch.setText("");
                        break;

                    }
                    if (rs2.isLast()) {
                        JOptionPane.showMessageDialog(null, "The Student is not there...!");
                    }
                }

                rs2.close();
                rs1.close();
            } catch (Exception e) {
                // JOptionPane.showMessageDialog(null, "Error");
                jTextFieldSearch.setText("");
            }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        currentRow = jTable2.getSelectedRow();
        if (currentRow == -1) {
            JOptionPane.showConfirmDialog(null, "Do not Select Row Yet...!");
        } else {
            try {
                model = (DefaultTableModel) jTable2.getModel();
                int id = (int) jTable2.getValueAt(currentRow, 0);
                updateOnDatabase("DELETE FROM marks WHERE marks.id_student=" + id + ";");
                updateOnDatabase("DELETE FROM notes. WHERE notes.id_student=" + id + ";");
                updateOnDatabase("DELETE FROM student WHERE student.id_student=" + id + ";");
                updateOnDatabase("DELETE FROM account WHERE account.id_account=" + id + ";");
                model.removeRow(currentRow);
                JOptionPane.showMessageDialog(null, "Done");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed

    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        currentRow = jTable2.getSelectedRow();
        if (currentRow == -1) {
            JOptionPane.showConfirmDialog(null, "Do not Select Row Yet...!");
        } else {
            try {
                model = (DefaultTableModel) jTable2.getModel();
                int id = (int) jTable2.getValueAt(currentRow, 0);
                updateOnDatabase("UPDATE student SET \n"
                        + "student.first_name='" + jTable2.getValueAt(currentRow, 1) + "',\n"
                        + "student.middle_name='" + jTable2.getValueAt(currentRow, 2) + "',\n"
                        + "student.last_name='" + jTable2.getValueAt(currentRow, 3) + "',\n"
                        + "student.mobile='" + jTable2.getValueAt(currentRow, 4) + "',\n"
                        + "student.Address='" + jTable2.getValueAt(currentRow, 5) + "'\n"
                        + "WHERE student.id_student=" + id + ";");
                model.setValueAt(jTable2.getValueAt(currentRow, 1), currentRow, 1);
                model.setValueAt(jTable2.getValueAt(currentRow, 2), currentRow, 2);
                model.setValueAt(jTable2.getValueAt(currentRow, 3), currentRow, 3);
                model.setValueAt(jTable2.getValueAt(currentRow, 4), currentRow, 4);
                model.setValueAt(jTable2.getValueAt(currentRow, 5), currentRow, 5);
                JOptionPane.showMessageDialog(null, "Done , Id and class do not Update...");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked

    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAddress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private static javax.swing.JComboBox jComboBox1;
    public static javax.swing.JComboBox jComboBoxMain;
    private javax.swing.JComboBox jComboBoxMarks;
    private javax.swing.JComboBox jComboBoxSubject;
    private javax.swing.JComboBox jComboBoxTeacher;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JTextField jFirstTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLastName;
    private javax.swing.JTextField jLastTeacher;
    private javax.swing.JTextField jMiddleName;
    private javax.swing.JTextField jMobile;
    private javax.swing.JTextField jMobileTeacher;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableMarks;
    private javax.swing.JTable jTableTeachar;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jfirstName;
    // End of variables declaration//GEN-END:variables
}
